# Gradle build.

name: Publish to package repository

# TODO fix this
#on: [push]
on:
  release:
    types: [created, published]

jobs:

  publish_to_registry:

    steps:

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish to github maven repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRAILS_VERSION: 4.0.5
        run: |
          ./gradlew publish
